// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package swagger

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Ortrix Maintainers",
            "url": "https://github.com/mayur-tolexo/ortrix"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/workflows/start": {
            "post": {
                "description": "Starts a new workflow execution",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflow"
                ],
                "summary": "Start a workflow",
                "parameters": [
                    {
                        "description": "Workflow input",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.StartWorkflowRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.StartWorkflowResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/workflows/{id}/status": {
            "get": {
                "description": "Returns the current status of a workflow",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "workflow"
                ],
                "summary": "Get workflow status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workflow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GetWorkflowStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Returns the health status of the gateway service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "Error is the error message.",
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "main.GetWorkflowStatusResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status is the current status of the workflow.",
                    "type": "string",
                    "example": "running"
                },
                "workflow_id": {
                    "description": "WorkflowID is the unique identifier of the workflow.",
                    "type": "string",
                    "example": "wf-abc123"
                }
            }
        },
        "main.StartWorkflowRequest": {
            "type": "object",
            "properties": {
                "input": {
                    "description": "Input is the JSON payload for the workflow.",
                    "type": "object",
                    "additionalProperties": true
                },
                "workflow_name": {
                    "description": "WorkflowName is the name of the workflow to execute.",
                    "type": "string",
                    "example": "order-processing"
                }
            }
        },
        "main.StartWorkflowResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message provides additional details.",
                    "type": "string",
                    "example": "workflow started successfully"
                },
                "status": {
                    "description": "Status is the current status of the workflow.",
                    "type": "string",
                    "example": "started"
                },
                "workflow_id": {
                    "description": "WorkflowID is the unique identifier of the started workflow.",
                    "type": "string",
                    "example": "wf-abc123"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Ortrix Gateway API",
	Description: "REST API for the Ortrix distributed workflow orchestrator.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
